baseURL = 'https://quantd1108.github.io/physicstranslate.github.io/'
languageCode = 'vi'
title = 'Physics Translate VN'
theme = 'PaperMod'

[params.profileMode]
  enabled = true
  title = "Physics Translate VN"
  subtitle = "Hub học thuật: Từ Vật lý Lý thuyết đến kỹ thuật 🚀"

  [[params.profileMode.buttons]]
    name = "Đọc Bản Demo Quang Sóng"
    url = "/projects/quang-song-demo/"

[[params.socialIcons]]
    name = "email"
    url = "mailto:physicstranslatevn@gmail.com"
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/QuanTD1108"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

  # Cấu hình MathJax để hiển thị LaTeX
  math = true 

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Tuyển tập Tài liệu"
    url = "/projects/"
    weight = 10
  [[menu.main]]
    identifier = "physicsinlife"
    name = "Physics In Life"
    url = "/pil/"
    weight = 20